using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Test.Waf.Foundation.SynchronizingCollectionCoreTest.#DisposeTest()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Scope = "type", Target = "Test.Waf.Foundation.ObservableListViewCoreTest")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Test.Waf.Foundation.ObservableListViewCoreTest.#RaiseEventsWithoutListener()")]
[assembly: SuppressMessage("Build", "CA1801:Parameter context of method ValidateAge is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:Test.Waf.Foundation.ValidatableModelTest.Person.ValidateAge(System.Int32,System.ComponentModel.DataAnnotations.ValidationContext)~System.ComponentModel.DataAnnotations.ValidationResult")]// This file is used by Code Analysis to maintain SuppressMessage 
[assembly: SuppressMessage("Design", "CA1052:Static holder types should be Static or NotInheritable", Justification = "<Pending>", Scope = "type", Target = "~T:Test.Waf.Presentation.Services.SettingsServiceCoreTest.DoubleNestedTypeTest")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Test.Waf.Presentation.Services.SettingsServiceCoreTest.ErrorOccurredTest")]
[assembly: SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:Test.Waf.Foundation.IPublisher.RaiseEvent")]
[assembly: SuppressMessage("Design", "CA1065:Do not raise exceptions in unexpected locations", Justification = "<Pending>", Scope = "member", Target = "~P:Test.Waf.Foundation.WeakEventErrorsChangedTest.Publisher.HasErrors")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1801:Avoid unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Test.Waf.Foundation.ValidationHelperTest.TypeValidationClass.TestValidate(Test.Waf.Foundation.ValidationHelperTest.TypeValidationClass,System.ComponentModel.DataAnnotations.ValidationContext)~System.ComponentModel.DataAnnotations.ValidationResult")]
