//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waf.BookLibrary.Library.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Waf.BookLibrary.Library.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        public static string AddMenu {
            get {
                return ResourceManager.GetString("AddMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address book.
        /// </summary>
        public static string AddressBook {
            get {
                return ResourceManager.GetString("AddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book library.
        /// </summary>
        public static string BookLibrary {
            get {
                return ResourceManager.GetString("BookLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book: {0}.
        /// </summary>
        public static string BookTitle {
            get {
                return ResourceManager.GetString("BookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+A.
        /// </summary>
        public static string ControlA {
            get {
                return ResourceManager.GetString("ControlA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+C.
        /// </summary>
        public static string ControlC {
            get {
                return ResourceManager.GetString("ControlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+S.
        /// </summary>
        public static string ControlS {
            get {
                return ResourceManager.GetString("ControlS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+V.
        /// </summary>
        public static string ControlV {
            get {
                return ResourceManager.GetString("ControlV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+X.
        /// </summary>
        public static string ControlX {
            get {
                return ResourceManager.GetString("ControlX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Y.
        /// </summary>
        public static string ControlY {
            get {
                return ResourceManager.GetString("ControlY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Z.
        /// </summary>
        public static string ControlZ {
            get {
                return ResourceManager.GetString("ControlZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string CopyMenu {
            get {
                return ResourceManager.GetString("CopyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email cannot be created. Please check that an email software is installed and configured..
        /// </summary>
        public static string CreateEmailError {
            get {
                return ResourceManager.GetString("CreateEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu_t.
        /// </summary>
        public static string CutMenu {
            get {
                return ResourceManager.GetString("CutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database: {0}.
        /// </summary>
        public static string DatabasePath {
            get {
                return ResourceManager.GetString("DatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Data.
        /// </summary>
        public static string DataMenu {
            get {
                return ResourceManager.GetString("DataMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        public static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string DeleteMenu {
            get {
                return ResourceManager.GetString("DeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1.
        /// </summary>
        public static string F1 {
            get {
                return ResourceManager.GetString("F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First_name.
        /// </summary>
        public static string FirstnameMenu {
            get {
                return ResourceManager.GetString("FirstnameMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string Isbn {
            get {
                return ResourceManager.GetString("Isbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lend to.
        /// </summary>
        public static string LendTo {
            get {
                return ResourceManager.GetString("LendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lend to:.
        /// </summary>
        public static string LendToCheck {
            get {
                return ResourceManager.GetString("LendToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string MoreButton {
            get {
                return ResourceManager.GetString("MoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New email message..
        /// </summary>
        public static string NewEmailMessage {
            get {
                return ResourceManager.GetString("NewEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string PasteMenu {
            get {
                return ResourceManager.GetString("PasteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish date.
        /// </summary>
        public static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        public static string RedoMenu {
            get {
                return ResourceManager.GetString("RedoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string RemoveMenu {
            get {
                return ResourceManager.GetString("RemoveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        public static string Reporting {
            get {
                return ResourceManager.GetString("Reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string SaveMenu {
            get {
                return ResourceManager.GetString("SaveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Search.
        /// </summary>
        public static string SearchMenu {
            get {
                return ResourceManager.GetString("SearchMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select _all.
        /// </summary>
        public static string SelectAllMenu {
            get {
                return ResourceManager.GetString("SelectAllMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Title.
        /// </summary>
        public static string TitleMenu {
            get {
                return ResourceManager.GetString("TitleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string UndoMenu {
            get {
                return ResourceManager.GetString("UndoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown application error
        ///
        ///{0}.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was returned.
        /// </summary>
        public static string WasReturnedCheck {
            get {
                return ResourceManager.GetString("WasReturnedCheck", resourceCulture);
            }
        }
    }
}
