//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waf.NewsReader.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Waf.NewsReader.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Feed.
        /// </summary>
        internal static string AddFeed {
            get {
                return ResourceManager.GetString("AddFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Management.
        /// </summary>
        internal static string DataManagement {
            get {
                return ResourceManager.GetString("DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Sync.
        /// </summary>
        internal static string DataSync {
            get {
                return ResourceManager.GetString("DataSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature synchronizes the feed list and read/unread status with multiple devices. A Microsoft account is required as the synchronization is using OneDrive..
        /// </summary>
        internal static string DataSyncDescription {
            get {
                return ResourceManager.GetString("DataSyncDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        internal static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Feed.
        /// </summary>
        internal static string EditFeed {
            get {
                return ResourceManager.GetString("EditFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter or paste the URL to a publication&apos;s RSS Feed below to add it to your list..
        /// </summary>
        internal static string EnterOrPasteFeedUrlBelow {
            get {
                return ResourceManager.GetString("EnterOrPasteFeedUrlBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Name.
        /// </summary>
        internal static string FeedName {
            get {
                return ResourceManager.GetString("FeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Url.
        /// </summary>
        internal static string FeedUrl {
            get {
                return ResourceManager.GetString("FeedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items: {0}.
        /// </summary>
        internal static string ItemsWithCount {
            get {
                return ResourceManager.GetString("ItemsWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Error.
        /// </summary>
        internal static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Month.
        /// </summary>
        internal static string OneMonth {
            get {
                return ResourceManager.GetString("OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Year.
        /// </summary>
        internal static string OneYear {
            get {
                return ResourceManager.GetString("OneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a feed..
        /// </summary>
        internal static string SelectFeedInfo {
            get {
                return ResourceManager.GetString("SelectFeedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share diagnostics file.
        /// </summary>
        internal static string ShareDiagnosticsFile {
            get {
                return ResourceManager.GetString("ShareDiagnosticsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Month.
        /// </summary>
        internal static string SixMonth {
            get {
                return ResourceManager.GetString("SixMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store at maximum feed items per feed:.
        /// </summary>
        internal static string StoreAtMaximumFeedItemsPerFeed {
            get {
                return ResourceManager.GetString("StoreAtMaximumFeedItemsPerFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store feed items for:.
        /// </summary>
        internal static string StoreFeedItemsFor {
            get {
                return ResourceManager.GetString("StoreFeedItemsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization: Activated.
        /// </summary>
        internal static string SynchronizationActivated {
            get {
                return ResourceManager.GetString("SynchronizationActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization: Deactivated.
        /// </summary>
        internal static string SynchronizationDeactivated {
            get {
                return ResourceManager.GetString("SynchronizationDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Month.
        /// </summary>
        internal static string ThreeMonth {
            get {
                return ResourceManager.GetString("ThreeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title: {0}.
        /// </summary>
        internal static string TitleWithParam {
            get {
                return ResourceManager.GetString("TitleWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        internal static string Unlimited {
            get {
                return ResourceManager.GetString("Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread.
        /// </summary>
        internal static string Unread {
            get {
                return ResourceManager.GetString("Unread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread: {0}.
        /// </summary>
        internal static string UnreadWithCount {
            get {
                return ResourceManager.GetString("UnreadWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
