//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waf.InformationManager.Assembler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Waf.InformationManager.Infrastructure.Modules.Presentation.dll</string>
  <string>Waf.InformationManager.Infrastructure.Modules.Applications.dll</string>
  <string>Waf.InformationManager.AddressBook.Modules.Presentation.dll</string>
  <string>Waf.InformationManager.AddressBook.Modules.Applications.dll</string>
  <string>Waf.InformationManager.EmailClient.Modules.Presentation.dll</string>
  <string>Waf.InformationManager.EmailClient.Modules.Applications.dll</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ModuleAssemblies {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ModuleAssemblies"]));
            }
        }
    }
}
