name: System.Waf.CI
on: 
  push:
    paths: 
    - 'src/*'
    - 'src/System.Waf/**'
    - 'src/Samples.UITest/**'
    - '.github/workflows/**' 

jobs:
  build:
    name: 🛠️ Build and test
    runs-on: windows-2022

    steps:
    - name: 🔖 Check-out
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: ⚙️ Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10'

    - name: 🛠️ Build
      run: dotnet build ./src/System.Waf/System.Waf.sln -c Release -p:ContinuousIntegrationBuild=true

    - name: 🕵️ Test
      run: |
        echo "## 🕵️ Test Results - System.Waf.sln" >> $Env:GITHUB_STEP_SUMMARY
        dotnet test ./src/System.Waf/System.Waf.sln -c Release --no-build --logger GitHubActions

    - name: 📦 Upload NuGet Packages
      uses: actions/upload-artifact@v4
      with:
        name: Packages
        if-no-files-found: error
        path: |
          src/System.Waf/System.Waf/**/*.nupkg
          src/System.Waf/System.Waf/**/*.snupkg

    - name: 🖥️ UI Test
      run: |
        echo "## 🕵️ Test Results - Samples.UITest.sln" >> $Env:GITHUB_STEP_SUMMARY
        dotnet test ./src/Samples.UITest/Samples.UITest.sln --logger GitHubActions -maxCpuCount:1

    - name: 🕵️ Code Coverage
      run: |
        dotnet tool update -g dotnet-coverage
        dotnet-coverage merge --output ./out/CodeCoverage/System.Waf.cobertura.xml --output-format cobertura "./src/**/TestResults/**/*.coverage"
        dotnet tool update -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:./out/CodeCoverage/System.Waf.cobertura.xml -targetdir:./out/CodeCoverage -reporttypes:"MarkdownSummaryGithub"
        echo "## 🕵️ Code Coverage" >> $Env:GITHUB_STEP_SUMMARY
        cat ./out/CodeCoverage/SummaryGithub.md >> $Env:GITHUB_STEP_SUMMARY
        
    - name: 📦 Upload UI Test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: UITestResults
        if-no-files-found: ignore
        path: |
          out/Samples.UITest/

    - name: 📦 Upload UI Test App logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: UITestAppLogs
        if-no-files-found: ignore
        path: |
          ~/AppData/Local/Waf Writer/Log/
          ~/AppData/Local/Waf Book Library/Log/
          ~/AppData/Local/Waf Information Manager/Log/
